[dependencies]
"php/php-32" = "=8.3.2101-rc.1"

[fs]
"/app" = "app"
"/test" = "test"


[[command]]
name = "run"
module = "php/php-32:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/test", "-S", "localhost:8080"]
